/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testRoll() {
        Library sut = new Library();
        int n = 4;
        int[] rolls = sut.roll(n);
        assertEquals(n, rolls.length);
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6);
        }
    }
    @Test
    @DisplayName("testing for dupliactes")
    public void testDuplicates() {
        Library sut = new Library();
//        int[] testArray = new int[]{1, 2, 2, 3};
        int[] testArray = {1, 2, 2, 3};
        boolean results = sut.containsDuplicates(testArray);
        assertTrue(results);
    }

    @Test
    @DisplayName("test average")
    public void testAverage(){
        Library sut = new Library();
        int[] testArr = {1,2,3};
        double actualAverage = sut.calculateAverage(testArr);
        assertEquals(2.0, actualAverage);
    }


}

//ChatGPT Help with test

