/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    void testRestaurant() {
        Restaurant restaurant1 = new Restaurant("A Restaurant", 2, 1);
        System.out.println(restaurant1.toString());
    }

    @Test
    void testReview() {
        Review review1 = new Review("Name", "Good", 3);
        String expectedReviewString = "Review{Author: Name, Body: Good, Rating: 3}";
        assertEquals(expectedReviewString, review1.toString(), "Review toString() output is incorrect");
    }
}

//ChatGPT help with assertEquals